---
- name: Download Wordpress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/var/www/wordpress-{{ wp_version }}.tar.gz
           sha256sum="{{ wp_sha256sum }}"
- unarchive: src=/var/www/wordpress-{{ wp_version }}.tar.gz dest=/var/www copy=no

- name : Copy wordpress files to www folder
  command: cp -r /var/www/wordpress/. /var/www/{{project['name']}}/

- name: Copy dump
  copy: src=dump.sql dest=/tmp

- name: Create Wordpress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Restore from dump
  mysql_db: name={{ wp_db_name }} state=import target=/tmp/dump.sql

- name: Create Wordpress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present

- name: Copy Wordpress config file
  template: src=wp-config.php dest=/var/www/{{project['name']}}/

- name: Change ownership of Wordpress installation
  file: path=/var/www/{{project['name']}}/ owner=www-data group=www-data state=directory recurse=yes