---
- name: Install mysql pkg
  action: apt pkg={{item}} state=installed
  with_items: mysql_pkgs

- name: Copy the my.cnf file 
  template: src=my.cnf dest={{ mysql_conf_dir }}/my.cnf
  notify: 
   - restart mysql

- name: Create the directory /etc/mysql/conf.d
  file: path=/etc/mysql/conf.d state=directory
  notify:
   - restart mysql

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
  with_items:
   - 127.0.0.1
   - ::1
   - localhost

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=~/.my.cnf mode=0600